import os
import re
from typing import Any, Dict, Optional, Tuple

from flask import Flask, render_template, request, jsonify, make_response
from openai import OpenAI
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# IMPORTANT: correct template/static paths for Vercel
# ExamCraft - AI-powered exam paper generator
app = Flask(
    __name__,
    template_folder="../templates",
    static_folder="../static"
)

# OpenAI client
api_key = os.environ.get("OPENAI_API_KEY")
if not api_key:
    # fail fast so the deploy log or local console shows the problem
    raise RuntimeError("OPENAI_API_KEY environment variable is required")

client = OpenAI(
    api_key=api_key
)

# -------------------------------
# Generate Question Paper
# -------------------------------

def generate_question_paper(data: Dict[str, Any]) -> str:
    """ExamCraft: Generate a question paper using OpenAI
    
    Args:
        data: Form data containing class, board, subject, difficulty, marks, etc.
    Returns:
        Generated question paper text
    """
    # assemble prompt pieces; keep it short so the model has room
    parts = [
        f"You are an expert {data['board']} exam paper setter.",
        "Generate a professional question paper.",
        f"Class: {data['class']}",
    ]
    if data.get('chapter'):
        parts.append(f"Chapter: {data['chapter']}")
    parts.extend([
        f"Subject: {data['subject']}",
        f"Difficulty: {data['difficulty']}",
        f"Total marks: {data['marks']}",
        "Follow official board exam pattern.",
        "Do not include answers or explanations.",
        "Use professional exam formatting.",
        "Sections: A) MCQ; B) Short Answer; C) Long Answer; D) Case Study."
    ])
    # board-specific advice
    if data.get('board') == 'Andhra Board':
        parts.append("Use Andhra Pradesh State Board style and syllabus hints.")
    if data.get('school_name'):
        parts.append(f"School: {data['school_name']}")
    if data.get('user_name'):
        parts.append(f"Generated by: {data['user_name']}")
    if data.get('include_key'):
        parts.append(
            "Also create an answer key on a separate page."
            " Start the key section with the text 'ANSWER KEY:' on its own line."
        )
    if data.get("instructions"):
        parts.append(f"Extra instructions: {data['instructions']}")

    prompt = "\n".join(parts)

    response = client.chat.completions.create(

        model="gpt-4o-mini",

        messages=[
            {
                "role": "system",
                "content": "You generate professional school exam papers."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],

        temperature=0.7
    )

    return response.choices[0].message.content


# -------------------------------
# Create PDF
# -------------------------------

def create_pdf(text: str, data: Dict[str, Any], key: Optional[str] = None) -> bytes:
    # use standard A4 size and reasonable margins
    pdf = FPDF(format='A4')
    pdf.set_left_margin(15)
    pdf.set_right_margin(15)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    font_path = os.path.join(
        os.path.dirname(__file__),
        "../static/fonts/DejaVuSans.ttf"
    )

    pdf.add_font("DejaVu", "", font_path)
    pdf.add_font("DejaVu", "B", font_path)

    pdf.set_font("DejaVu", "B", 16)

    # try to add a logo if one exists in static/images/logo.png
    logo_path = os.path.join(os.path.dirname(__file__), "../static/images/logo.png")
    if os.path.exists(logo_path):
        try:
            pdf.image(logo_path, x=10, y=8, w=30)
        except Exception:
            pass

    header_text = f"{data['board']} Examination"
    if data.get('school_name'):
        header_text = f"{data['school_name']} - " + header_text

    pdf.cell(
        0,
        10,
        header_text,
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
        align="C"
    )

    pdf.set_font("DejaVu", "", 12)

    pdf.cell(0, 8, f"Class: {data['class']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, f"Subject: {data['subject']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, f"Marks: {data['marks']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if data.get('user_name'):
        pdf.cell(0, 8, f"Prepared by: {data['user_name']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(10)

    pdf.multi_cell(0, 7, text)

    # append key on new page if provided
    if key:
        pdf.add_page()
        pdf.set_font("DejaVu", "B", 14)
        pdf.cell(0, 10, "Answer Key", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        pdf.set_font("DejaVu", "", 12)
        pdf.ln(5)
        pdf.multi_cell(0, 7, key)

    return bytes(pdf.output(dest="S"))


# -------------------------------
# Routes
# -------------------------------

@app.route("/")
def home():
    return render_template("index.html")


def split_key(text: str) -> Tuple[str, Optional[str]]:
    """Separate answer key from paper text if marker exists."""
    # look for the phrase 'answer key' on its own line (case insensitive)
    match = re.split(r"(?i)^answer key[:]?\s*", text, maxsplit=1, flags=re.MULTILINE)
    if len(match) == 1:
        return text, None
    main, key = match[0].strip(), match[1].strip()
    return main, key


def get_chapters_from_openai(class_num: str, subject: str, board: str) -> list:
    """ExamCraft: Fetch available chapters for given class, subject, and board from OpenAI."""
    prompt = f"""You are an educational expert. List ONLY the chapter names for {subject} in class {class_num} from {board} curriculum.
    Format: Return ONLY a comma-separated list of chapter names without numbering. Be brief.
    Example: "Real Numbers, Polynomials, Linear Equations, Quadratic Equations"
    """
    
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "system",
                "content": "You are an educational curriculum expert. Return concise lists of chapter names."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.5,
        max_tokens=200
    )
    
    chapters_text = response.choices[0].message.content.strip()
    # Split by comma and clean up
    chapters = [ch.strip() for ch in chapters_text.split(",") if ch.strip()]
    return chapters

@app.route("/generate", methods=["POST"])
def generate():
    try:
        data = request.json or {}

        # supply defaults
        if "board" not in data or not data["board"]:
            data["board"] = "Andhra Board"

        # validate input
        required = ["class", "board", "subject", "difficulty", "marks"]
        for field in required:
            if field not in data or data[field] in (None, ""):
                raise ValueError(f"'{field}' is required")
        # chapter is optional but if provided must not be empty
        if "chapter" in data and data["chapter"] in (None, ""):
            data.pop("chapter")

        # ensure numeric marks and class
        try:
            data["marks"] = int(data["marks"])
        except Exception:
            raise ValueError("'marks' must be a number")

        # optional text fields: user_name, school_name
        if "user_name" in data and not data["user_name"]:
            data.pop("user_name")
        if "school_name" in data and not data["school_name"]:
            data.pop("school_name")

        # determine if we need key
        want_key = bool(data.get("include_key"))

        full_text = generate_question_paper(data)
        paper, key_text = split_key(full_text) if want_key else (full_text, None)

        pdf_bytes = create_pdf(paper, data, key=key_text)

        return jsonify({
            "success": True,
            "paper": full_text,
            "pdf": pdf_bytes.decode("latin-1")
        })
    except Exception as e:
        # log the exception for debugging (in serverless this goes to logs)
        app.logger.error("generate() failed", exc_info=e)
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500


@app.route("/get-chapters", methods=["POST"])
def get_chapters():
    """Get available chapters for the selected class, subject, and board."""
    try:
        data = request.json or {}
        
        class_num = data.get("class")
        subject = data.get("subject")
        board = data.get("board", "Andhra Board")
        
        if not class_num or not subject:
            raise ValueError("Class and subject are required")
        
        chapters = get_chapters_from_openai(class_num, subject, board)
        
        return jsonify({
            "success": True,
            "chapters": chapters
        })
    except Exception as e:
        app.logger.error("get_chapters() failed", exc_info=e)
        return jsonify({
            "success": False,
            "error": str(e),
            "chapters": []
        }), 500


@app.route("/download", methods=["POST"])
def download():

    pdf_bytes = request.json["pdf"].encode("latin-1")

    response = make_response(pdf_bytes)

    response.headers.set("Content-Type", "application/pdf")

    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="question_paper.pdf"
    )

    return response


# CRITICAL FOR VERCEL
app = app


# Allow running locally with `python api/index.py`
if __name__ == "__main__":
    # development server, not for production
    app.run(debug=True, port=int(os.environ.get("PORT", 3000)))
